-- MySQL Script generated by MySQL Workbench
-- 10/22/18 19:14:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Id_Cliente` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Apellido` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Contraseña` VARCHAR(45) NULL COMMENT '',
  `Telefono` INT NULL COMMENT '',
  `Tarjeta_credito` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`Id_Cliente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Distribuidora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Distribuidora` (
  `Id_Distribuidora` INT NOT NULL COMMENT '',
  `Tipo_ Distribuidora` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Id_Distribuidora`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `Id_Sede` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Ciudad` VARCHAR(45) NULL COMMENT '',
  `Direccion` VARCHAR(45) NULL COMMENT '',
  `Distribuidora_Id_Distribuidora` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Sede`)  COMMENT '',
  CONSTRAINT `fk_Sede_Distribuidora1`
    FOREIGN KEY (`Distribuidora_Id_Distribuidora`)
    REFERENCES `mydb`.`Distribuidora` (`Id_Distribuidora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sede_Distribuidora1_idx` ON `mydb`.`Sede` (`Distribuidora_Id_Distribuidora` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pelicula` (
  `Id_Pelicula` INT NOT NULL COMMENT '',
  `Titulo` VARCHAR(45) NULL COMMENT '',
  `Genero` VARCHAR(45) NULL COMMENT '',
  `Clasificacion` VARCHAR(45) NULL COMMENT '',
  `Actores` VARCHAR(45) NULL COMMENT '',
  `Director` VARCHAR(45) NULL COMMENT '',
  `Duracion` VARCHAR(45) NULL COMMENT '',
  `Sede_Id_Sede` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Pelicula`, `Sede_Id_Sede`)  COMMENT '',
  CONSTRAINT `fk_Pelicula_Sede1`
    FOREIGN KEY (`Sede_Id_Sede`)
    REFERENCES `mydb`.`Sede` (`Id_Sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pelicula_Sede1_idx` ON `mydb`.`Pelicula` (`Sede_Id_Sede` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `Id_Sala` INT NOT NULL COMMENT '',
  `Capacidad` VARCHAR(45) NULL COMMENT '',
  `Detalle_confort` VARCHAR(45) NULL COMMENT '',
  `Nivel_sonido` VARCHAR(45) NULL COMMENT '',
  `Calidad_Equipo` VARCHAR(45) NULL COMMENT '',
  `Pelicula_Id_Pelicula` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Sala`)  COMMENT '',
  CONSTRAINT `fk_Sala_Pelicula1`
    FOREIGN KEY (`Pelicula_Id_Pelicula`)
    REFERENCES `mydb`.`Pelicula` (`Id_Pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sala_Pelicula1_idx` ON `mydb`.`Sala` (`Pelicula_Id_Pelicula` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Acomodador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acomodador` (
  `Id_Acomodador` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Apellido` VARCHAR(45) NULL COMMENT '',
  `Telefono` INT NULL COMMENT '',
  `Sala_Id_Sala` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Acomodador`, `Sala_Id_Sala`)  COMMENT '',
  CONSTRAINT `fk_Acomodador_Sala`
    FOREIGN KEY (`Sala_Id_Sala`)
    REFERENCES `mydb`.`Sala` (`Id_Sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Acomodador_Sala_idx` ON `mydb`.`Acomodador` (`Sala_Id_Sala` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Venta_Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta_Entrada` (
  `Id_ventas` INT NOT NULL COMMENT '',
  `Valor_Total` VARCHAR(45) NULL COMMENT '',
  `Cliente_Id_Cliente` INT NOT NULL COMMENT '',
  `Pelicula_Id_Pelicula` INT NOT NULL COMMENT '',
  `Sede_Id_Sede` INT NOT NULL COMMENT '',
  `Tarjeta_credito` VARCHAR(45) NULL COMMENT '',
  `Hora` VARCHAR(45) NULL COMMENT '',
  `Sala` VARCHAR(45) NULL COMMENT '',
  `Fecha` VARCHAR(45) NULL COMMENT '',
  `Num_Asiento` VARCHAR(45) NULL COMMENT '',
  `Lugar_Asiento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Id_ventas`, `Pelicula_Id_Pelicula`)  COMMENT '',
  CONSTRAINT `fk_Venta_Entrada_Cliente1`
    FOREIGN KEY (`Cliente_Id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Entrada_Pelicula1`
    FOREIGN KEY (`Pelicula_Id_Pelicula`)
    REFERENCES `mydb`.`Pelicula` (`Id_Pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Entrada_Sede1`
    FOREIGN KEY (`Sede_Id_Sede`)
    REFERENCES `mydb`.`Sede` (`Id_Sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Venta_Entrada_Cliente1_idx` ON `mydb`.`Venta_Entrada` (`Cliente_Id_Cliente` ASC)  COMMENT '';

CREATE INDEX `fk_Venta_Entrada_Pelicula1_idx` ON `mydb`.`Venta_Entrada` (`Pelicula_Id_Pelicula` ASC)  COMMENT '';

CREATE INDEX `fk_Venta_Entrada_Sede1_idx` ON `mydb`.`Venta_Entrada` (`Sede_Id_Sede` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `Id_Horario` INT NOT NULL COMMENT '',
  `Hora_Pelicula` VARCHAR(45) NULL COMMENT '',
  `Dia_Pelicula` VARCHAR(45) NULL COMMENT '',
  `Sala` VARCHAR(45) NULL COMMENT '',
  `Pelicula_Id_Pelicula` INT NOT NULL COMMENT '',
  `Venta_Entrada_Id_ventas` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Horario`)  COMMENT '',
  CONSTRAINT `fk_Horario_Pelicula1`
    FOREIGN KEY (`Pelicula_Id_Pelicula`)
    REFERENCES `mydb`.`Pelicula` (`Id_Pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Venta_Entrada1`
    FOREIGN KEY (`Venta_Entrada_Id_ventas`)
    REFERENCES `mydb`.`Venta_Entrada` (`Id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Horario_Pelicula1_idx` ON `mydb`.`Horario` (`Pelicula_Id_Pelicula` ASC)  COMMENT '';

CREATE INDEX `fk_Horario_Venta_Entrada1_idx` ON `mydb`.`Horario` (`Venta_Entrada_Id_ventas` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `Id_Login` INT NOT NULL COMMENT '',
  `Usuario` VARCHAR(45) NULL COMMENT '',
  `Contraseña` VARCHAR(45) NULL COMMENT '',
  `Cliente_Id_Cliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Login`, `Cliente_Id_Cliente`)  COMMENT '',
  CONSTRAINT `fk_Login_Cliente1`
    FOREIGN KEY (`Cliente_Id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Login_Cliente1_idx` ON `mydb`.`Login` (`Cliente_Id_Cliente` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
